services:
- docker
sudo: true
language: python
python:
- '3.6'
cache:
- pip
jobs:
  include:
  - stage: test
    install:
      - pip install -U codecov
      - pip install -r requirements-dev.txt
    script:
      - coverage run --source main -m pytest
    after_success:
      - codecov
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambdalint_black
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAUYKBYPB2QY2HG57F
      secret_access_key:
        secure: "jxmli56L2Jj6g8R/bvTN/Gb8E1iMJGXdDPoRnfeNUtkizoVICO5rj4z5jXi0oJ6OOauI/so/A8CgPUBmfhzRSTQtZaYVSh9I2vQSJilGAtlHB79y22CMZS5sEKJeik78jMK8I77V1KkTGq2cpF96GdK7X/FPU9OFCfB3k2MS46e7JLvfg4PcWvh6g06vmt72tk4ArqS1Ke0rJMuWs2bmR3t7Hl8DAtY+HjPABsJb0z10FINeLs2eQVgLpYICwnGHGNa6lRWXbnLlEIgb234KD9mpNBLb62y/tVwjONrebctOakcOnTfvZ4FxggtKaprjyPC26UkYQsXREjDu8Aw3X9+fYr1cekCt5B2dp0yE/uZH/rBYNP/9wgHAgDZqLVL8nFDp5bfLyM9BCFlMptkvBNcPAAuE59LZQhDFQCFZEscTejt9am9bpe3Kxlla/xEUzp7peeRUpFR9JlRvwxMhKEIK5L2Z2EHhqZ600/o/gma+G09sxE4WC8cmDo+VbUUecOR1TUd/Lq75USgrjSaTTDLQ8E1vM7ydEdPEim12XoBUrUPKoOHB751jJvdUdhumXfpbk4nNM7fRiGGx9HXARdPd5rkdn1Uz8p5tCutIrJwtYNTPa5uRKSfCYyR6hLIFKX5Py7WD/NXfcTkfXjknxxCKQhdImZ88I7aPgLC+/V8="
      on:
        repo: FussyFox/black
