services:
- docker
sudo: true
language: python
python:
- '3.6'
cache:
- pip
jobs:
  include:
  - stage: test
    install:
      - pip install -U codecov
      - pip install -r requirements-dev.txt
    script:
      - coverage run --source main -m pytest
    after_success:
      - codecov
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambdalint_black
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAUYKBYPB2TWLLNJ7K
      secret_access_key:
        secure: "XIiTUZdEGBkvWWx6uUlt9UHk1oleUB1qLmZVU+FCUVLhrkZedC2ZLONtGeGgQmPuVaWNvNdjAWXc1iaznI8mU3obDswN4jQHkSqXl1slWznsi3TfjTrSCcta80R46xVbyQtHcIGLu/k4edXx5+6w6xYiEvhLLGiMU7QN0nZoGGIFSzJhjrja5jjYMMrkJ9NmvKs+GRM/UQtjv3TQA8yE1z3dAaOn8Jgf6TQOjpucwvtNay5hiJts7uGB+9XGbyIvnKV3VPn9K/abNvZ3qLnd7jtZ7v7wlSSbFfc+zKVeKPdL09U6aYydYpUulQnUwAy+zTEBeiJKbi6jxCA8wXV/RBn5JFknHO/6bnwc9e6GWlI4qy/foGGgJCU6f9gF2SjtmG50mHYh1FKi2G03urhjQpmMoQmYJI9PVkLwoGQ0RN8oaZdZhSnN/HxumSCkqdOE/HFRvWmtdCFRMKdMjkzzU9R5REWhbvuZcpgO//sCZZAkULzrm7CCa35iFzeYtPnVdCzQ0GQmmxJJQawDXiPYxYamX3fvtgkLPTQB4nOvi/eTQ1yaF64RzgpyUESi0gOErYiP79e7ebuMpSZlFvHynmRk1q/zJV6rSoPs9fhgzTpYkEgQd1bn3oJQOaGaiFzV7qBX1slPd/bPKjIcIN/qbU55KWDADZLUFNDoBBuzfWo="
      on:
        repo: FussyFox/black
