services:
- docker
sudo: true
language: python
python:
- '3.6'
cache:
- pip
jobs:
  include:
  - stage: test
    install:
      - pip install -U codecov
      - pip install -r requirements-dev.txt
    script:
      - coverage run --source main -m pytest
    after_success:
      - codecov
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambdalint_black
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAJTUSZCFJO2PNDFHQ
      secret_access_key:
        secure: "FxiIcbsBB2CC/3gzGgJHZTwWWreCwcTNhQ9LIYiTq8OkpVtRjdGhZVZyOEf3hZuie58ISXWvC9cVNISpJ5V1YYl7d3/jsTLNH7JEkHk0DEW+VnfOdKy21ZVfsU02TWVCdbYYfnbqlyMBUYo/9GkVIFq5BUkesXEFIC9LZ38DXZ1FzQuKbR+hx3X3ZM8WKMNJDE5n6P5mf4wba7aZjpg9zG3A32YtR6l4Zk5oaZ/XggQkjtxZ5cd+bVZX92UuW1thv3EHHvru3AwrOLgsbc+TQ+e0YdP5ITxqipKE3J4bDrsW+5D5T/la1VlzoCYBbRiwUksrSMhkpikuyh/9Zc8sNVuQp/31Seqgxb4/VRrLi+yeNYbmsj+Bx4UnOI8lnXvb8spRd7Cv3wiiiX6WoNUAhZO67uhKHKj1sRr96CE0m4CYncGIvPKt9cn2VQZRrlqfJ5ni0RwisuNaAmTZGP5PT+g94gRdVTUQ3IfhG/+kBJfS4+xzebInJUJQhsGZkHJDbYrGgQospnlJrxXN3w1lCmQsNYoF0UvOPtXt5p2g/p2DzJsxaLEvVZZM6w3zHLIh83Ngpj7qidq/wgHp+QU/6sosok5D0Wrhdg6WQVMZPIzmvz7pgPYiCyYRW0lo1vmwo6DipWKNtkA6c2kXJh7gkgIUAaH9bml+LnR6dTWrc0g="
      on:
        repo: FussyFox/black
